coretech: Move to newer style
* fixes kernel/oneplus/sm8150/coretech/memplus/core/memplus_core.c:123:30: error: this old-style function definition is not preceded by a prototype [-Werror,-Wstrict-prototypes]
bool ctech_current_is_swapind()